name: Zombies
main: com.pwncraftpvp.zombies.core.Main
description: Zombies!
author: JjPwN1
version: 1.0
depend: [HolographicDisplays, zComms]
commands:
   zombies:
      description: Modify the plugin!
   z:
      description: Modify the plugin!
   vote:
      description: Vote for a map!